### ISSUE TITLE
Media playback/controls is broken on some websites

### ISSUE THREAD

**Issue by wsdfhjxc** [wsdfhjxc/expose-noisy-tabs#20]
When the extension is enabled there is a problem with media playback and lack of controls on some websites such as [Reuters](http://www.reuters.com/article/us-northkorea-missiles-kcna-idUSKBN16D2MC?feedType=RSS&feedName=topNews&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+reuters%2FtopNews+%28News+%2F+US+%2F+Top+News%29). The [injected overriding script](https://github.com/wsdfhjxc/expose-noisy-tabs/blob/8d8fb2c5c12792e37d19e47c7950a9afa66a1b5a/bootstrap.js#L271-L295) is the cause of this behavior and probably of #17 as well. These webpages seem not to like this kind of hacks.

**Comment by adisib** [comment]
There is a div on the Reuters page that updates its class when the video is hovered over. The div has an id of "app" and is the child of another div with the same id (which is bound to cause problems) which is in the body of an iframe. When the extension is enabled, the div no longer updates in response to the mouse hovering over the video.

There doesn't seem to be a DOM difference as far as I can tell. Perhaps the script is stripping the mouseover event listener? That shouldn't result in DOM elements missing for 17 however.
