### ISSUE TITLE
Ability to mute tabs in advance

### ISSUE THREAD

**Issue by pip25** [wsdfhjxc/expose-noisy-tabs#24]
A similar feature in Firefox lets you mute a tab irrespective of whether it is playing any audio at that time by selecting the "Mute tab" option from the tab's right click menu. This would be very useful to have in this extension too, especially for webapps that have short notification sounds (and thus the speaker icon only appears for a second or two).

**Comment by adisib** [comment]
The creator has been missing for a while, and I'm only familiar with javascript, not extension development. Thus I don't know how to do this, though I can look into it later when I have time if you would like as I think this is a useful feature.

**Comment by pip25** [comment]
I've looked into how to change tab context menus, and it's a pain, apparently. However, it seems your fix for #25 already took care of this, in a way: pressing CTRL+M on a tab mutes it regardless of whether any sound is currently playing, and this setting sticks until the tab is closed. Perhaps the only thing missing functionality-wise is that there is no visual feedback for CTRL+M; it would likely be a good option to show the muted speaker icon on a muted tab regardless of whether any sound is currently playing (that's what Firefox does, too).

**Comment by adisib** [comment]
Ok, but I wouldn't want this to be confused as indicating that a muted sound is playing, vs muted without any sound playing. The difference could be whether there is a sound wave coming out of the speaker icon, but for the available icons it looks to be rather small so might be a little more difficult to notice than is ideal if it is indicated that way. Even if that was ideal, not all of the icon options (such as the headphone or speaker) have a sound wave that could be utilized in this way. I agree that it would be nice to indicate the mute state even when it isn't relevant at the current moment, but I don't want to introduce a bigger problem of being misleading on what is currently happening on the page. Much less importantly, the icons are minified in what appears to be a lossy way to me, and not all of the icons have their originals in the repository. This could lead to inconsistent icon quality if I were to edit them.

Maybe there is a better way to distinguish a muted tab vs muted media other than changing the icon, but I don't have any ideas as to what that might be.

**Comment by pip25** [comment]
Well, on Firefox I think the icon is only shown if the whole tab is muted, while here the muted icon is also shown if the controls on the page itself muted the sound that is supposed to be playing (so the muting was not done by the extension). I thought of this as a nice bonus, but if it is confusing, it'd be possible to restrict the "muted" icon's appearance to situations where the tab has been muted by the extension (ENT_MUTED_ATTRIBUTE) and not the page controls.

**Comment by adisib** [comment]
Ok, that makes more sense. That way there isn't the confusion and you are describing what the extension is doing properly.

I agree that the muted icon describing the tab mute state is better than describing the page's media element states if the change to make muting persist on tabs is made. I can do this change if you want, unless you want to update your pull request instead.

**Comment by pip25** [comment]
I'll try updating my pull request with this shortly.

**Comment by wsdfhjxc** [comment]
Thank you! I've merged your improvements. Tab context menu support has been also added.
