### ISSUE TITLE
Issue with missing close button on middle clicked links

### ISSUE THREAD

**Issue by DjZiio** [wsdfhjxc/expose-noisy-tabs#27]
Using this add-on with Tab Mix Plus there is an issue with middle clicked links not having a close button on the tab on some sites. I tested with all other add-ons disabled. I tried the newest dev build of TMP and still had the issue, though it doesn't happen on every site nor does the site have to have audio for it to occur. The site I've been testing with is https://moviebobcentral.com/ middle click "About Moviebob" at the top of the page and the tab has no close button with both add-ons installed; I've tested it with all the different settings for close button under Display/Tab in TMP. It happens on many other sites as well though most that don't have any audio so I don't know why there is an issue and I have had no other issue with the program running in tandem with TMP before the last Pale Moon update and on the majority of sites I visit. I love this add-on so I thought I'd bring it to you attention and hope its something that's an easy fix. Let me know if you need any more info or clarification.

**Comment by DjZiio** [comment]
Using this add-on with Tab Mix Plus there is an issue with middle clicked links not having a close button on the tab on some sites. I tested with all other add-ons disabled. I tried the newest dev build of TMP and still had the issue, though it doesn't happen on every site nor does the site have to have audio for it to occur.  The site I've been testing with is https://moviebobcentral.com/  middle click "About Moviebob" at the top of the page and the tab has no close button with both add-ons installed; I've tested it with all the different settings for close button under Display/Tab in TMP.  It happens on many other sites as well though most that don't have any audio so I don't know why there is an issue and I have had no other issue with the program running in tandem with TMP before the last Pale Moon update and on the majority of sites I visit. I love this add-on so I thought I'd bring it to you attention and hope its something that's an easy fix. Let me know if you need any more info or clarification.

**Comment by CandyAngel** [comment]
This happens without TMP as I've raised this issue myself (#28) and I don't use TMP.

**Comment by DjZiio** [comment]
I downloaded the version that was mentioned in the second comment in the first thread in the closed section, it looks like a fork off an older build, 0.8
0, but it fixed my problem instantly. I'm still keeping an eye on the original release and hoping it gets fixed as well because I like the option to change the color to grey in 1.0.0.

**Comment by DjZiio** [comment]
I downloaded the version that was mentioned in the second comment in the first thread in the closed section, it looks like a fork off an older build, 0.8.0, but it fixed my problem instantly. I'm still keeping an eye on the original release and hoping it gets fixed as well because I like the option to change the color to grey in 1.0.0.

**Comment by DjZiio** [comment]
Sorry about the double post, #25 is the thread I was talking about, in case something else gets closed.

**Comment by wsdfhjxc** [comment]
Please try version 1.0.1.

**Comment by DjZiio** [comment]
Thanks, works great
