### ISSUE TITLE
Icon not displayed on the Soundcloud page

### ISSUE THREAD

**Issue by xbeyond1** [wsdfhjxc/expose-noisy-tabs#6]
![1](https://cloud.githubusercontent.com/assets/22633092/19930870/fe7c3252-a112-11e6-8a79-24829fa6d858.png)

**Comment by xbeyond1** [comment]
Also, I tried to listen to a Soundcloud clip on an embedded link on reddit, and the icon wasn't displayed either. YouTube clips work fine there.

![2](https://cloud.githubusercontent.com/assets/22633092/19931010/9a1fedfc-a113-11e6-898a-5b228cae7976.png)

**Comment by adisib** [comment]
Soundcloud seems to play directly through javascript, never appending any HTML5 media elements to the DOM. Something like ```
var sound = new Audio('sound.mp3');
sound.play();
``` If it isn't on the DOM, I don't think there is any way for the extension to see it. It is likely that the embedded player does the same thing, but I would have to check.

**Comment by xbeyond1** [comment]
It does work perfectly with Firefox; perhaps checking their code out or something will help?

**Comment by wsdfhjxc** [comment]
Actually, there is a way to detect all sound sources in a browser's window that I've just found out. Pale Moon seems to emit `media-playback` [event](https://github.com/MoonchildProductions/Pale-Moon/blob/5214789d035f4e4c08899a6e281116520f605ec6/dom/audiochannel/AudioChannelService.cpp#L152-L154) in a scope of a window when something starts playing. It requires an additional preference `media.useAudioChannelService` set to `true` to get this work. [Here](https://github.com/MoonchildProductions/Pale-Moon/blob/5214789d035f4e4c08899a6e281116520f605ec6/dom/base/test/test_audioNotification.html) is even a test for this. Maybe this could solve all issues if it was integrated.

**Comment by wsdfhjxc** [comment]
Unfortunately, `media-playback` isn't a viable solution with PM's AudioChannelService implementation.

**Comment by wsdfhjxc** [comment]
Solved by c26250c.
