### ISSUE TITLE
Icon not displayed with videos on CNN.com and BBC.com

### ISSUE THREAD

**Issue by xbeyond1** [wsdfhjxc/expose-noisy-tabs#7]
For example:
http://www.bbc.com/travel/story/20160502-bavarias-bizarre-bell-ringing
http://edition.cnn.com/2016/11/02/us/iowa-police-shooting/index.html

**Comment by adisib** [comment]
From the readme: 

> Works only with HTML5 media elements.

The video players on this page use Flash, rather than HTML5 media elements. There is no way for the extension to be able to tell they are playing.

**Comment by wsdfhjxc** [comment]
The BBC website provides the video in HTML5 but doesn't work either.

**Comment by wsdfhjxc** [comment]
The video from CNN seems to be kind of causing the indicator to show up. Not sure if the recent change really fixed this or just got lucky.

**Comment by xbeyond1** [comment]
Still doesn't work here, neither it 0.20 nor 0.21.

**Comment by xbeyond1** [comment]
Reuters.com doesn't work either. I guess it suffers from the same problem as CNN and BBC.

http://www.reuters.com/article/us-facebook-results-idUSKBN12X2HU

**Comment by wsdfhjxc** [comment]
Probably the CNN video loads for you as a Flash embedded element. The same about Reuters as it requires having Flash plugin installed from what I can see. It's not supported at the moment. Sorry for the inconvenience.

**Comment by xbeyond1** [comment]
No problem. I hope I'm not begin too annoying by pointing out all the faults this early. :P
