### ISSUE TITLE
Icon does not work with Spotify's webplayer

### ISSUE THREAD

**Issue by xbeyond1** [wsdfhjxc/expose-noisy-tabs#9]
The title says it all. :)

![spoti](https://cloud.githubusercontent.com/assets/22633092/19933990/e1bc0948-a11d-11e6-9086-ccbeef68d512.png)

**Comment by adisib** [comment]
Unfortunately, Spotify is still relying on Flash for audio playback. It doesn't work here for the same reasons as #7 .
